---
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - wget -q https://releases.hashicorp.com/terraform/0.12.13/terraform_0.12.13_linux_amd64.zip
      - unzip terraform_0.12.13_linux_amd64.zip
      - mv terraform /usr/local/bin/terraform
      - uname -a
  pre_build:
    commands:
      - echo '0. initiate terraform'
      - terraform init -no-color
      - echo '1. executing terraform fmt'
      - terraform fmt -no-color
  build:
    commands:
      - echo '2. executing terraform plan -var-file="starter.tfvars" '
      - |
          if [ ${STAGE} == "TEST" ] ; then
            echo "${STAGE}"
          fi
      - if [ ${STAGE} == "DEPLOY" ] ; then  terraform plan -var-file="starter.tfvars" -no-color ; fi
      - if [ ${STAGE} == "DEPLOY" ] ; then  echo "yes" | terraform apply -var-file="starter.tfvars" -no-color ; fi


  post_build:
    commands:
      - echo '3. gonna make the Magic'
      - echo ${STAGE}

